"""cambio de xp a exp

Revision ID: 244dd88727a1
Revises: a00e22c2b3e5
Create Date: 2026-05-14 15:48:01.429230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244dd88727a1'
down_revision: Union[str, Sequence[str], None] = 'a00e22c2b3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('focus_sessions', sa.Column('exp_earned', sa.Integer(), nullable=False))
    op.drop_column('focus_sessions', 'xp_earned')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('focus_sessions', sa.Column('xp_earned', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('focus_sessions', 'exp_earned')
    # ### end Alembic commands ###
