"""empty message

Revision ID: 9fe1a5d07a6a
Revises: 244dd88727a1
Create Date: 2026-05-26 14:43:30.207028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe1a5d07a6a'
down_revision: Union[str, Sequence[str], None] = '244dd88727a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_focus_sessions_user_id'), 'focus_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_focus_sessions_user_id'), table_name='focus_sessions')
    # ### end Alembic commands ###
