"""Creacion tabla focus_sessions

Revision ID: a00e22c2b3e5
Revises: 
Create Date: 2026-05-14 10:55:59.613822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import advanced_alchemy

# revision identifiers, used by Alembic.
revision: str = 'a00e22c2b3e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('focus_sessions',
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('user_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('room_id', advanced_alchemy.types.guid.GUID(length=16), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('start_time', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('end_time', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_focus_sessions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('focus_sessions')
    # ### end Alembic commands ###
